### ISSUE TITLE
Preparation 1 Issue

### ISSUE THREAD

**Issue by dykesb** [STA518-01-SS21/community#1]
We've all had a pretty *interesting* past year... What is one thing that you are proud of accomplishing during our year+ of social distancing? I'll start...

I have applied for four research assistants (two grad and two undergrad) and have so far been 50% successful (the other two are currently under review)! I very much like being able to pay students, but it is even nicer when it is other people's money 💰

**Comment by begaliyk** [comment]
I have started doing **yoga**  and learned some new songs to play on *piano*

**Comment by 1hartl** [comment]
One thing I am proud of accomplishing this year is learning how to do new --skateboard-- **yo-yo** tricks

**Comment by liam-hart** [comment]
One thing I am proud of accomplishing this year is learning how to do new ~~skateboard~~ **yo-yo** tricks

**Comment by poirieca** [comment]
## One Thing I'm proud of?
I'm now an *advanced* napper

**Comment by defranks2323** [comment]
I am proud that I passed all my classes *last semester* and I got **engaged**.

**Comment by tkishbaugh** [comment]
I am proud for consistently doing the following *three* things every day:
* walk my dog
* go for a run
* spend time with my family

**Comment by jensengvsu** [comment]
One thing I am proud of accomplishing:
* Passing _all_ of my classes last semester

**Comment by allysonoco** [comment]
I am proud:
-  I started a job with **Pfizer** 
- and got a *puppy*

**Comment by BenBurkholder** [comment]
I am proud of the following:
* Creating a digital version of one of my favorite *board games*.
* Building a *table* to play it on.

**Comment by CarsenB** [comment]
##  What I am proud of:
   - I managed getting a 4.000 throughout my entire **junior year**.

**Comment by KMiedema** [comment]
I am proud that:
* I maintained a *decent* sleep schedule throughout this past year of **online school** and lack of work.

**Comment by kruskies** [comment]
### **I'm proud that**
even through _COVID_ I was able to maintain a good workout schedule and even find other ways to stay active besides **weight lifting** when the gyms were closed.

**Comment by a-duimstra** [comment]
I am proud that my new dog is *finally* able to sleep through an **entire** night and that I can too!

**Comment by katiewebster** [comment]
I am *pretty* proud that I am now SAS 9.4 Programming Fundamentals **certified**.

**Comment by vangurik** [comment]
**SAS Work**

I had completed my **SAS project** and learned regression models in _SAS_, hoping to learn same in my STA518

**Comment by Barri9999** [comment]
I proud that I got my cryptos with my hard earned savings  and they doubled

**Comment by shahnikcode** [comment]
I am very proud that I have maintained a 4.0 average with: 
1. two kids
2. one internship
3. one voluntary teaching commitment
4. 6 months of a new job
5. my daughter *finally* eating solid foods! 
 Im also very proud Im perfectly functional on *four* cups of coffee daily!

**Comment by travrad** [comment]
I'm proud of having kept up with school and work, all while managing living through a pandemic. Its been a lot to handle, but it is worthwhile to sit back and notice the accomplishment.

**Comment by asmush** [comment]
I am proud to be a new **gecko mom** to my baby boy, *Grandpa*.
