### ISSUE TITLE
Preparation02 BB Instructions

### ISSUE THREAD

**Issue by poirieca** [STA518-01-SS21/community#10]
On Blackboard the Preparation02 submission asks that we submit a clickable link to the Learning Journal repository for evidence of completing Preparation02. Should it be asking for a link to the Preparation02 repo instead?

**Comment by dykesb** [comment]
Sorry, that is confusing and even the Preparation 2 README directions are not very clear (i.e., in Task 5 it says "Submit the link to this GitHub repo on Blackboard as a clickable link for evidence of completing Preparation 2.").

Both the Preparation 2 README and Preparation 2 Bb item should instead be:

> Submit the link to your newly created `<username>/preparation02` GitHub repo as a *clickable link* for evidence of completing Preparation 2.

I will update this in both places now.
