### ISSUE TITLE
activity 3.1: Issue when running `stringr::str_c(...)` code at end

### ISSUE THREAD

**Issue by shahnikcode** [STA518-01-SS21/community#18]
I think i finally got my code right but i dont know if i didn't overwrite my top_secret file correctly or if i didn't put the dataframes together with my_symbols correctly that my code didn't produce a message.  Would you be able to help me troubleshoot what I might have done wrong?

1. Add 14 to every number.
2. Multiply every number by 18, then subtract 257.
3. Exponentiate every number.  (That is, do e ^ [number]. You may need to Google this!)
4. Square every number.

```{r}
secret14 <- c(top_secret +14)

secret4 <- c(secret14 * 18)

secret257 <- c(secret4 -257)

secretexp <- c(exp(secret257))
secretsquare <-c(secretexp^2)
```

**HQ UPDATE:** Headquarters has informed you that at this stage of decoding, there should be 548 numbers in the secret message that are below 17.

5. Turn your vector of numbers into a matrix with 5 columns.
6. Separately from your top secret numbers, create a vector of all the even numbers between 1 and 260. Name it "evens". That is, "evens" should contain 2, 4, 6, 8, ..., 260.
7. Subtract the "evens" vector from the first column of your secret message matrix.
8. Subtract 100 from all numbers 18-24th rows of the 3rd column.
9. Multiply all numbers in the 4th and 5th column by 2.
10. Turn your matrix back into a vector.

```{r}
newmatrix= matrix(secretsquare, ncol = 5)
evens<- seq(from = 2, to = 260, by = 2)
newmatrix[,1]= newmatrix[,1]-evens

newmatrix[18:24,3] <- newmatrix[18:24,3] - 100

newmatrix[,4:5] <- newmatrix[,4:5] * 2

newmatrix <- c(newmatrix)
```

**HQ UPDATE:** Headquarters has informed you that at this stage of decoding, all numbers in indices 500 and beyond are below 100.

11. Take the square root of all numbers in indices 38 to 465.
12. Round all numbers to the nearest whole number.
13. Replace all instances of the number 39 with 20.

```{r}
newmatrixsqrt <- c(sqrt(newmatrix [38:465]))
newmatrix2 <- replace(newmatrix, c(38:465), newmatrixsqrt)
newmatrixround<- round(newmatrix2,digits=0)
newmatrixround[newmatrixround == 39] <- 20

newmatrixround3 <- newmatrixround[ newmatrixround %% 2 == 0]
```

**HQ UPDATE:** Headquarters has informed you that your final message should have 466 even numbers.

```{r}
stringr::str_c(my_symbols$Symbol[top_secret], collapse= ", ")
```

**Comment by dykesb** [comment]
Your final object is called `newmatrixround3`, but I am assuming that is called `top_secret`. These need to be the same for my `stringr::str_c(...)` call to work.

**Comment by shahnikcode** [comment]
So should i create a new line that says top_secret<-newmatricround3?

**Comment by dykesb** [comment]
Try it and see if that accomplishes what you are trying to do.

**Comment by shahnikcode** [comment]
So when I gave it a try and left this code as `stringr::str_c(my_symbols$Symbol[top_secret], collapse= " ")`, i still dont see a message.  All I see is " ".

**Comment by shahnikcode** [comment]
Also, if it helps, here is what i did prior to translating the code before line 117:
---
title: "Activity 3.1"
author: "Azure"
output: github_document
---

Today you will be creating and manipulating vectors, lists, and data frames to uncover a top secret message.

As you work through this document with your Team members, remember to:

- Ask questions
- Google is your friend!
  If an error is confusing, copy it into Google and see what other people are saying.
  If you don't know how to do something, search for it.
- Just because there is no error message doesn't mean everything went smoothly.
  Use the console to check each step and make sure you have accomplished what you wanted to accomplish.

Do not edit this first R code chunk.
This will allow you to knit your document and view errors within the knitted report.

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

### Setup

Each of the following R chunks will cause an error and/or do the desired task incorrectly.  Find the mistake, and correct it to complete the intended action.

Create three vectors that contain: 1) the lower case letters, 2) the lower case letters, and 3) some punctuation marks.

```{r}
lower_case <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z")

upper_case <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z")

punctuation <- c(".", ",", "!", "?", "'", "'", "(", ")", " ", "-", ";", ":")
```

Comment on what you noticed about the errors and how you used this information to correct the issues.


Make one long vector containing all the symbols.

```{r}
my_symbols <- c(lower_case, upper_case, punctuation)
```

Comment on what you noticed about the errors and how you used this information to correct the issues.


Turn the `my_symbols` vector into a data frame, with the variable name "Symbol".

```{r}
my_symbols <- as.data.frame(my_symbols)

Symbol <- names(my_symbols)
```

Find the total number of symbols we have in our data frame.  

```{r}
len <- nrow(my_symbols)
```

Comment on what you noticed about the errors and how you used this information to correct the issues.


5. Create a new variable in your dataframe that assigns a number to each symbol.

```{r}
my_symbols_num <- 1:len
```



![](README-img/noun_pause.png) **Planned Pause Point**: If things made sense, feel free to continue on while you wait. Otherwise, contact your instructor to have them verify your work.


### Decoding the secret message.

This chunk will load up the encoded secret message data and assign it as a vector.
There are no errors here.

```{r}
# Read in full csv file
top_secret <- readr::read_csv("data/secret_code.csv", col_names = FALSE)

# Pick off only the column X1
top_secret <- top_secret$X1

**Comment by dykesb** [comment]
I noticed that your final object (`newmatrixround3`) is not actually the vector, this is your check to see how many even values are in your vector so you would need to instead use your final object.

Also, your `my_symbols` data frame does not have two columns: `Symbol` and `Num`. I would recommend going through each line to see if it produces the results being asked of you.

**Comment by shahnikcode** [comment]
So here is what I did to remedy the my_symbols problem:
my_symbols <- data.frame(my_symbols)
colnames(my_symbols)
names(my_symbols)[colnames(my_symbols) == "my_symbols"] <- "symbol"


```


Find the total number of symbols we have in our data frame.  

```{r}
len <- nrow(my_symbols)
```

Comment on what you noticed about the errors and how you used this information to correct the issues.

**Response**: We have 64 symbols


5. Create a new variable in your dataframe that assigns a number to each symbol.

```{r}
num <- c(1:len)
df<-data.frame(my_symbols, num)
my_symbols<-df

```



![](README-img/noun_pause.png) **Planned Pause Point**: If things made sense, feel free to continue on while you wait. Otherwise, contact your instructor to have them verify your work.


### Decoding the secret message.

This chunk will load up the encoded secret message data and assign it as a vector.
There are no errors here.

```{r}
# Read in full csv file
top_secret <- readr::read_csv("data/secret_code.csv", col_names = FALSE)

# Pick off only the column X1
top_secret <- top_secret$X1

```

so when I use the following code this is what I get:
```{r}
newmatrixsqrt <- c(sqrt(newmatrix [38:465]))
newmatrix2 <- replace(newmatrix, c(38:465), newmatrixsqrt)
newmatrixround<- round(newmatrix2,digits=0)
newmatrixround[newmatrixround == 39] <- 20
top_secret <-newmatrixround


```

Use your final vector of numbers as indices for `my_symbols` to discover the final message, by running the following code:

```{r}
stringr::str_c(my_symbols$symbol[top_secret], collapse= " ")
```



[1] "C o m e   g a t h e r   ' r o u n d   p e o p l e ,   w h e r e v e r   y o u   r o a m   A n d   a d m i t   t h a t   t h e   w a t e r s   a r o u n d   y o u   h a v e   g r o w n   A n d   a c c e p t   i t   t h a t   s o o n   y o u ' l l   b e   d r e n c h e d   t o   t h e   b o n e   I f   y o u r   t i m e   t o   y o u   i s   w o r t h   s a v i n g   T h e n   y o u   b e t t e r   s t a r t   s w i m m i n '   o r   y o u ' l l   s i n k   l i k e   a   s t o n e   F o r   t h e   t i m e s ,   t h e y   a r e   a - c h a n g i n '     C o m e   w r i t e r s   a n d   c r i t i c s   w h o   p r o p h e s i z e   w i t h   y o u r   p e n   A n d   k e e p   y o u r   e y e s   w i d e ,   t h e   c h a n c e   w o n ' t   c o m e   a g a i n   A n d   d o n ' t   s p e a k   t o o   s o o n ,   f o r   t h e   w h e e l ' s   s t i l l   i n   s p i n   A n d   t h e r e ' s   n o   t e l l i n '   w h o   t h a t   i t ' s   n a m i n '   F o r   t h e   l o s e r   n o w   w i l l   b e   l a t e r   t o   w i n   F o r   t h e   t i m e s ,   t h e y   a r e   a - c h a n g i n '     C o m e   s e n a t o r s ,   c o n g r e s s m e n ,   p l e a s e   h e e d   t h e   c a l l   D o n ' t   s t a n d   i n   t h e   d o o r w a y ,   d o n ' t   b l o c k   u p   t h e   h a l l   F o r   h e   t h a t   g e t s   h u r t   w i l l   b e   h e   w h o   h a s   s t a l l e d   T h e   b a t t l e   o u t s i d e   r a g i n '   W i l l   s o o n   s h a k e   y o u r   w i n d o w s   a n d   r a t t l e   y o u r   w a l l s   F o r   t h e   t i m e s ,   t h e y   a r e   a - c h a n g i n '     C o m e   m o t h e r s   a n d   f a t h e r s   t h r o u g h o u t   t h e   l a n d   A n d   d o n ' t   c r i t i c i z e   w h a t   y o u   c a n ' t   u n d e r s t a n d   Y o u r   s o n s   a n d   y o u r   d a u g h t e r s   a r e   b e y o n d   y o u r   c o m m a n d   Y o u r   o l d   r o a d   i s   r a p i d l y   a g i n g   P l e a s e   g e t   o u t   o f   t h e   n e w   o n e   i f   y o u   c a n ' t   l e n d   y o u r   h a n d   F o r   t h e   t i m e s ,   t h e y   a r e   a - c h a n g i n '   T h e   l i n e ,   i t   i s   d r a w n ,   t h e   c u r s e ,   i t   i s   c a s t   T h e   s l o w   o n e   n o w   w i l l   l a t e r   b e   f a s t   A s   t h e   p r e s e n t   n o w   w i l l   l a t e r   b e   p a s t   T h e   o r d e r   i s   r a p i d l y   f a d i n g   A n d   t h e   f i r s t   o n e   n o w   w i l l   l a t e r   b e   l a s t   F o r   t h e   t i m e s ,   t h e y  "
--
&nbsp;
&gt; | &gt;
&gt;



Naturally, evens would just give me consanants so to get the vowels I needed the odds also.  Thank you for making me realize it!

**Comment by dykesb** [comment]
It looks like you added a space between the two quotation marks in my `stringr::str_c(...)` (i.e., `collapse = " "` instead of `collapse = ""`)code which is making your output look odd (putting a space between all symbols).

Aside, while your method of naming the columns of your dataframe works, remember that you can name a column within `data.frame`: `data.frame(name = vector)`.

**Comment by shahnikcode** [comment]
> It looks like you added a space between the two quotation marks in my `stringr::str_c(...)` (i.e., `collapse = " "` instead of `collapse = ""`)code which is making your output look odd (putting a space between all symbols).
> 
> Aside, while your method of naming the columns of your dataframe works, remember that you can name a column within `data.frame`: `data.frame(name = vector)`.

Thank you for this! I fixed the code, and I will give the data.frame(name=column) a try as well!
