### ISSUE TITLE
Project 2 Data

### ISSUE THREAD

**Issue by dykesb** [STA518-01-SS21/community#24]
Use this Issue to 1) view dataset that others are using and 2) post the data that you are including for your Project 2. Remember that this needs to be a named link like this: 

[GVSU Homepage](https://www.gvsu.edu)

Not this:

https://www.gvsu.edu

**Comment by Barri9999** [comment]
[covid-19 vaccine at county level](https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh)

**Comment by dykesb** [comment]
@Barri9999 please name this with something that is more meaningful to the link. Think along the lines of something related to the source and theme of the data.

**Comment by a-duimstra** [comment]
[Unemployment and Educational Attainment by County, From the USDA Economic Research Service](https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/)

**Comment by shahnikcode** [comment]
[Michigan County level Census 2010-2019](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-detail.html)

**Comment by allysonoco** [comment]
[County Level Smoking Data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VZ21KD)

**Comment by kruskies** [comment]
[County Presidential Election Returns 2000-2020](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VOQCHQ)

**Comment by begaliyk** [comment]
[Poverty estimates for the U.S., States, and counties, 2019 from the Economic Research Service, USDA](https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/)

**Comment by tkishbaugh** [comment]
[County-Level Demographic Data](https://www.openintro.org/data/?data=county_complete)

**Comment by ConnorSickmiller115** [comment]
[https://data.world/albert/us-county-level-uv-exposure](url)

**Comment by dykesb** [comment]
@ConnorSickmiller115 please name make this a named link as others have done.

**Comment by soniyaadhi** [comment]
[Poverty Level & Access to Internet ](https://www.ahrq.gov/sdoh/data-analytics/sdoh-tech-poverty.html),[Health Risks](http://www.healthdata.org/us-health/data-download)

**Comment by katiewebster** [comment]
[County level cancer death data](https://gis.cdc.gov/Cancer/USCS/#/StateCounty/)

**Comment by travrad** [comment]
[County Level Population Change, USA 2010 - 2019](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html#par_textimage_70769902)

**Comment by BenBurkholder** [comment]
[`2020 traffic crash data`](https://www.michigantrafficcrashfacts.org/querytool/table/0#q1;0;2020;;)

**Comment by liam-hart** [comment]
[Unemployment and median household income for the U.S., States, and counties, 2000-20](https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/)

**Comment by KMiedema** [comment]
[Jail Death Data](https://www.reuters.com/investigates/special-report/usa-jails-graphic/)
