### ISSUE TITLE
Project 4 Visualizations

### ISSUE THREAD

**Issue by dykesb** [STA518-01-SS21/community#25]
Use this Issue to 1) view visualizations that others are using and 2) post the visualization that you are recreating for your Project 4. Remember that this needs to be a named link like this: 

[GVSU Homepage](https://www.gvsu.edu)

Not this:

https://www.gvsu.edu

**Comment by poirieca** [comment]
[Road Traffic Deaths](https://ourworldindata.org/grapher/road-traffic-deaths-sdgs)

[Causes of death in 50-69 year olds](https://ourworldindata.org/grapher/causes-of-death-in-50-69-year-olds?country=~OWID_WRL)

[Diarrheal Disease Death Rates](https://ourworldindata.org/grapher/diarrheal-death-rates-vs-sanitation )

[Relative Coverage of Death](https://ourworldindata.org/grapher/death-coverage-in-nyt)

**Comment by liam-hart** [comment]
[Are we working more than ever?](https://ourworldindata.org/working-more-than-ever)

[Self-reported Life Satisfaction vs GDP per capita, 2018](https://ourworldindata.org/happiness-and-life-satisfaction)

[Time use](https://ourworldindata.org/time-use?country=)

[Urban and rural population projected to 2050, World, 1500 to 2050](https://ourworldindata.org/urbanization)

**Comment by allysonoco** [comment]
[Cutting down forests: what are the drivers of deforestation? ](https://ourworldindata.org/what-are-drivers-deforestation)

[The world now produces more seafood from fish farms than wild catch](https://ourworldindata.org/rise-of-aquaculture)

[Who emits more than their share of CO₂ emissions?](https://ourworldindata.org/share-co2-emissions)

[Global inequalities in CO₂ emissions, based on consumption](https://ourworldindata.org/global-inequalities-co2-consumption)

**Comment by vangurik** [comment]
[Air Population Deaths as percentage of Global disease burden](https://ourworldindata.org/grapher/air-pollution-deaths-as-percentage-of-global-disease-burden) 
[Death rate from ambient particulate air pollution,2017](https://ourworldindata.org/grapher/outdoor-pollution-death-rate)
[Outdoor air pollution death rates by age, World, 2017](https://ourworldindata.org/grapher/outdoor-pollution-rates-by-age?country=~OWID_WRL)
[Death Rates from air pollution,World,1990 to 2017](https://ourworldindata.org/grapher/death-rate-by-source-from-air-pollution?country=~OWID_WRL)

**Comment by Pallapup** [comment]
Fertility can decline extremely fast.

Skepticism to vaccines and what to do about it

We've updated our entry on trade and globalization

How many people support vaccination across the world?

**Comment by Pallapup** [comment]
[How many people support vaccination across the world?](https://ourworldindata.org/support-for-vaccination)

[Skepticism to vaccines and what to do about it](https://ourworldindata.org/vaccine-skepticism)

[Fertility can decline extremely fast](https://ourworldindata.org/fertility-can-decline-extremely-fast)

[We've updated our entry on trade and globalization](https://ourworldindata.org/weve-updated-our-entry-on-trade-and-globalization)

**Comment by soniyaadhi** [comment]
[Deaths based on different Risk Factors](https://ourworldindata.org/grapher/number-of-deaths-by-risk-factor?country=~OWID_WRL)
[Deaths due to Obesity](https://ourworldindata.org/grapher/share-of-deaths-obesity?tab=chart )
[Prevalence of Eating Disorder ](https://ourworldindata.org/grapher/number-with-an-eating-disorder?country=~OWID_WRL)
[% of men, women using social media](https://ourworldindata.org/grapher/percent-of-men-and-women-using-social-media-platforms-in-the-us )

**Comment by a-duimstra** [comment]
[Land use per kilogram of food product](https://ourworldindata.org/grapher/land-use-per-kg-poore)
[Share of the global greenhouse gas emissions from food](https://ourworldindata.org/grapher/share-global-food-emissions?tab=chart&time=earliest..2015)
[Contribution to value added vs. share of CO2 emissions](https://ourworldindata.org/grapher/value-added-vs-share-of-emissions-usa)
[Greenhouse gas emissions from food systems, 2015 map](https://ourworldindata.org/grapher/emissions-from-food)

**Comment by shahnikcode** [comment]
[Share of primary school teachers who are female](https://ourworldindata.org/grapher/number-of-teachers-across-education-levels?country=~OWID_WRL)
[Number of new books purchased by year](https://ourworldindata.org/books)
[Literate and Illiterate population by year](https://ourworldindata.org/literacy)
[Users of Social media by platform and year](https://ourworldindata.org/internet)

**Comment by katiewebster** [comment]
[Share of total expenditure spent on food vs. food expenditure per person](https://ourworldindata.org/grapher/share-of-total-expenditure-spent-on-food-vs-food-expenditure-per-person)
[Food expenditure per person per year](https://ourworldindata.org/grapher/food-expenditure-per-person-per-year?tab=chart)
[Food expenditure as a share of family disposable income, United States](https://ourworldindata.org/grapher/food-expenditure-as-share-of-family-disposable-income?country=~USA)
[How much food can you buy for working one hour in the manufacturing sector?](https://ourworldindata.org/grapher/how-much-food-can-you-buy-for-working-one-hour-in-the-manufacturing-sector)

**Comment by begaliyk** [comment]
[Economic decline in the second quarter of 2020](https://ourworldindata.org/grapher/economic-decline-in-the-second-quarter-of-2020)
[Economic decline in the second quarter of 2020 vs rate of confirmed deaths due to COVID-19](https://ourworldindata.org/grapher/q2-gdp-growth-vs-confirmed-deaths-due-to-covid-19-per-million-people)
[Percentage of persons without health insurance in the US](https://ourworldindata.org/grapher/percentage-of-persons-without-health-insurance-coverage-us?time=earliest..2015)
[US healthcare expenditure](https://ourworldindata.org/grapher/us-healthcare-expenditure?country=~USA)
