### ISSUE TITLE
Project 5 Packages

### ISSUE THREAD

**Issue by dykesb** [STA518-01-SS21/community#31]
Use this Issue to 1) view packages that others are using and 2) post the packages that you are exploring for your Project 5. Remember that this needs to be a named link like this: 

[GVSU Homepage](https://www.gvsu.edu)

Not this:

https://www.gvsu.edu

**Comment by allysonoco** [comment]
[ggforce](https://ggforce.data-imaginist.com/)

[echarts4R](https://echarts4r.john-coene.com/articles/get_started.html)

[janitor](http://sfirke.github.io/janitor/)

**Comment by poirieca** [comment]
[XLConnect](https://cran.rstudio.com/web/packages/XLConnect/)

[ggiraph](https://cran.r-project.org/web/packages/ggiraph/index.html)

[maps](https://cran.r-project.org/web/packages/maps/index.html)

**Comment by vangurik** [comment]
[ggExtra](https://deanattali.com/2015/03/29/ggExtra-r-package/)

[ggpubr](https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html)

[e1071](https://cran.r-project.org/web/packages/e1071/index.html)

[caret](https://topepo.github.io/caret/)

**Comment by Pallapup** [comment]
[rvest](https://cran.r-project.org/web/packages/rvest/rvest.pdf)

[RSQLite](https://cran.r-project.org/web/packages/RSQLite/index.html)

[JSONlite](https://cran.r-project.org/web/packages/jsonlite/index.html)

**Comment by dykesb** [comment]
@Pallapup You will need to choose a package other than `{rvest}` (we will be using this today) and it is created by the RStudio team.

**Comment by Barri9999** [comment]
[C5.0](https://cran.r-project.org/web/packages/C50/vignettes/C5.0.html)

[rpart](https://www.rdocumentation.org/packages/rpart/versions/4.1-15/topics/rpart)

[factroextra](http://www.sthda.com/english/wiki/factoextra-r-package-easy-multivariate-data-analyses-and-elegant-visualization)

**Comment by soniyaadhi** [comment]
[Swirl](https://www.r-project.org/nosvn/pandoc/swirl.html)
[arules](https://cran.r-project.org/web/packages/arules/index.html)
[randomForest](https://cran.r-project.org/web/packages/randomForest/index.html)

**Comment by shahnikcode** [comment]
[SASExport](https://cran.r-project.org/web/packages/SASxport/index.html)
[quantmod](http://www.quantmod.com/)
[budgetr](https://github.com/derek-damron/budgetr)

**Comment by dykesb** [comment]
@soniyaadhi we have already used `{magrittr}` in class - this is where the pipe (`%>%`) comes from. Please select a new package.

**Comment by tkishbaugh** [comment]
[cellranger](https://github.com/rsheets/cellranger#readme)
[js](https://github.com/jeroen/js)
[RVerbalExpressions](https://github.com/VerbalExpressions/RVerbalExpressions)

**Comment by ConnorSickmiller115** [comment]
[Survival package](https://www.rdocumentation.org/packages/survival/versions/3.2-11)
[GGanimate](https://gganimate.com/)

**Comment by ConnorSickmiller115** [comment]
[GGanimate](https://gganimate.com/)

**Comment by travrad** [comment]
[MailR](https://github.com/rpremraj/mailR)
[Esquisse](https://github.com/dreamRs/esquisse)
[Cowsay](https://github.com/sckott/cowsay)

**Comment by begaliyk** [comment]
[DataExplorer](https://cran.r-project.org/web/packages/DataExplorer/index.html)
[furniture](https://cran.r-project.org/web/packages/furniture/index.html)
[tmap](https://cran.r-project.org/web/packages/tmap/index.html)

**Comment by 1hartl** [comment]
[gitcreds](https://cran.r-project.org/web/packages/gitcreds/index.html)
[calendR](https://cran.r-project.org/web/packages/calendR/index.html)
[tidylog](https://cran.r-project.org/web/packages/tidylog/index.html)

**Comment by liam-hart** [comment]
[calendR](https://cran.r-project.org/web/packages/calendR/index.html)
[tidylog](https://cran.r-project.org/web/packages/tidylog/index.html)
[wesanderson](https://cran.r-project.org/web/packages/wesanderson/index.html)

**Comment by katiewebster** [comment]
[`{checkpoint}`](https://cran.r-project.org/web/packages/checkpoint/index.html)
[`{dotwhisker}`](https://CRAN.R-project.org/package=dotwhisker)
[`{crosstable}`](https://cran.r-project.org/web/packages/crosstable/index.html)

**Comment by a-duimstra** [comment]
[finalfit](https://github.com/ewenharrison/finalfit/blob/master/README.md)
[skimr](https://github.com/ropensci/skimr/)
[visdat](https://github.com/ropensci/visdat)

**Comment by CarsenB** [comment]
[vtable](https://github.com/NickCH-K/vtable)
[snakecase](https://github.com/Tazinho/snakecase)
[crayon](https://github.com/r-lib/crayon)

**Comment by BenBurkholder** [comment]
[waffle](https://github.com/hrbrmstr/waffle)
[prettyunits](https://github.com/r-lib/prettyunits)
[xkcd]( https://CRAN.R-project.org/package=xkcd)

Edit: I was unable to get the xkcd package to work correctly and could not properly describe waffle so I chose replacments:
[DataEditR](https://github.com/DillonHammill/DataEditR)
[beepR](https://github.com/rasmusab/beepr)
