### ISSUE TITLE
Rstudio Cloud Primer Error

### ISSUE THREAD

**Issue by liam-hart** [STA518-01-SS21/community#35]
When trying to complete preparation 16, I am not able to advance past the first code chunk. When I try to run the code it gives me an error: "Error initiating session for external requests". Please try again later. I tried this over the weekend and thought it may be temporary, but the issue is persisting.

**Comment by CarsenB** [comment]
> When trying to complete preparation 16, I am not able to advance past the first code chunk. When I try to run the code it gives me an error: "Error initiating session for external requests". Please try again later. I tried this over the weekend and thought it may be temporary, but the issue is persisting.

I agree, I am having the same issue as well.

**Comment by dykesb** [comment]
I am seeing that some have already submit their screenshots so I assume that it works. Try clearing your cache, using a browser in private mode, or trying a different browser if you have more than one on your machine.

**Comment by liam-hart** [comment]
I tried all 3 of those options and I am still getting the same error. I googled it and found one Rstudio community post talking about the same issue, but it was posted 15 hours ago and has not yet received a reply.

**Comment by katiewebster** [comment]
I have been trying to attempt the primers for over a day and they also are not working for me. I have tried different browsers, clearing the cache, and using it in "incognito" mode. I'm not sure what I'm supposed to do at this point. I'll try to just click through without the code running and see how far it lets me go.

**Comment by ConnorSickmiller115** [comment]
Same issue here
